SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY,  SUM(A.PRICE * C.SALES) AS TOTAL_SALES
  FROM BOOK AS A
  JOIN AUTHOR AS B ON (A.AUTHOR_ID = B.AUTHOR_ID)
  JOIN BOOK_SALES AS C ON (A.BOOK_ID = C.BOOK_ID)
 WHERE C.SALES_DATE LIKE '2022-01%'
 GROUP BY A.AUTHOR_ID, A.CATEGORY
 ORDER BY AUTHOR_ID, CATEGORY DESC;