-- 코드를 입력하세요
SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
from REST_INFO AS RI
JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS 'FAVOIRTE'
     FROM REST_INFO
     GROUP BY FOOD_TYPE
     ) AS MR
ON RI.FOOD_TYPE = MR.FOOD_TYPE AND RI.FAVORITES = MR.FAVOIRTE
order by RI.FOOD_TYPE DESC;