WITH USECAR AS (
    SELECT A.CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR AS A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON (A.CAR_ID = B.CAR_ID)
    WHERE A.CAR_TYPE IN ("세단", "SUV") 
    AND (START_DATE >= "2022-11-01" AND START_DATE <= "2022-11-30") 
    OR (END_DATE >= "2022-11-01" AND END_DATE <= "2022-11-30") 
    OR (START_DATE <= "2022-11-01" AND END_DATE >= "2022-11-30") 
) , CARINFO AS (
    SELECT CAR_ID, CAR_TYPE, CASE
        WHEN CAR_TYPE = "세단" THEN ROUND(DAILY_FEE * 30 * (100 -(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = "세단" AND DURATION_TYPE LIKE "%30%")) * 0.01)
        WHEN CAR_TYPE = "SUV" THEN ROUND(DAILY_FEE * 30 * (100 -(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = "SUV" AND DURATION_TYPE LIKE "%30%")) * 0.01)
        END AS FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_ID NOT IN (SELECT CAR_ID FROM USECAR)
    AND CAR_TYPE IN ("세단", "SUV")
)

SELECT CAR_ID, CAR_TYPE, FEE
FROM CARINFO
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;