WITH TSIZE AS (
    SELECT ID, ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS NUM
      FROM ECOLI_DATA
)

SELECT ED.ID, CASE 
            WHEN TS.NUM <= (SELECT COUNT(*) FROM TSIZE) / 4 
            THEN 'CRITICAL'
            WHEN TS.NUM <= (SELECT COUNT(*) FROM TSIZE) / 2
            THEN 'HIGH'
            WHEN TS.NUM <= (SELECT COUNT(*) FROM TSIZE) / 4 * 3 
            THEN 'MEDIUM'
            ELSE 'LOW'
        END AS COLONY_NAME 
  FROM ECOLI_DATA AS ED JOIN TSIZE AS TS ON (ED.ID = TS.ID)
 ORDER BY ID;