WITH GET_NUM AS (
    SELECT ID, ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS ROWNUM
      FROM ECOLI_DATA
)

SELECT ID, 
        CASE
            WHEN ROWNUM <= ((SELECT COUNT(*) AS CNT FROM ECOLI_DATA) / 4)
            THEN 'CRITICAL'
            WHEN ROWNUM <= ((SELECT COUNT(*) AS CNT FROM ECOLI_DATA) / 2)
            THEN 'HIGH'
            WHEN ROWNUM <= ((SELECT COUNT(*) AS CNT FROM ECOLI_DATA) / 4 * 3)
            THEN 'MEDIUM'
            ELSE 'LOW'
        END AS 'COLONY_NAME'
  FROM GET_NUM
 ORDER BY ID