-- 코드를 입력하세요
WITH USERS AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),
SALES AS (
    SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT USER_ID) AS PURCHASED_USERS
    FROM ONLINE_SALE
    WHERE USER_ID IN (SELECT USER_ID FROM USERS)
    GROUP BY DATE_FORMAT(SALES_DATE, "%Y-%M")
),
USER_CNT AS(
    SELECT COUNT(*) CNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT YEAR, MONTH, PURCHASED_USERS, ROUND(PURCHASED_USERS/ (
    SELECT CNT FROM USER_CNT), 1) AS PUCHASED_RATIO
FROM SALES
ORDER BY YEAR, MONTH;
