WITH RENTDAY AS (
    SELECT DATEDIFF(END_DATE, START_DATE) + 1 AS DAY, HISTORY_ID, CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT B.HISTORY_ID, 
        CEILING(CASE 
            WHEN B.DAY >= 90
            THEN A.DAILY_FEE * B.DAY * (100 - (
                SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
                WHERE DURATION_TYPE = 90 AND CAR_TYPE = '트럭')) / 100
            WHEN B.DAY >= 30
            THEN A.DAILY_FEE * B.DAY * (100 - (
                SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
                WHERE DURATION_TYPE = 30 AND CAR_TYPE = '트럭')) / 100
            WHEN B.DAY >= 7
            THEN A.DAILY_FEE * B.DAY * (100 - (
                SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
                WHERE DURATION_TYPE = 7 AND CAR_TYPE = '트럭')) / 100
            ELSE A.DAILY_FEE * B.DAY
        END) AS FEE
  FROM CAR_RENTAL_COMPANY_CAR AS A JOIN
        RENTDAY  AS B
        ON (A.CAR_ID = B.CAR_ID)
 WHERE A.CAR_TYPE = '트럭'
 ORDER BY FEE DESC, B.HISTORY_ID DESC;
   

