-- 코드를 입력하세요
with recursive temp as(
    select 0 as HOUR
    union all
    select HOUR+1 from temp where HOUR<23
),
ANIMAL_TIME AS (
    SELECT ANIMAL_ID, CASE
    WHEN SUBSTR(DATETIME, 12, 2) LIKE "0%" THEN SUBSTR(DATETIME, 13, 1)
    ELSE SUBSTR(DATETIME, 12, 2)
    END AS HOUR, COUNT(*) AS CNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR
)

SELECT T.HOUR, CASE 
    WHEN (SELECT CNT FROM ANIMAL_TIME AS B WHERE B.HOUR = T.HOUR )  > 0 THEN A.CNT
    ELSE 0 END AS COUNT
FROM TEMP AS T LEFT JOIN ANIMAL_TIME AS A ON(T.HOUR = A.HOUR)
ORDER BY T.HOUR;


# select * from temp;