WITH RECURSIVE TIMES AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM TIMES WHERE HOUR < 23
), ADOPT AS (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(ANIMAL_ID) AS COUNT
    FROM ANIMAL_OUTS 
    GROUP BY HOUR
)

SELECT A.HOUR, CASE
    WHEN A.HOUR IN (SELECT HOUR FROM ADOPT) THEN B.COUNT
    ELSE 0
    END AS COUNT
FROM TIMES AS A LEFT JOIN ADOPT AS B ON (A.HOUR = B.HOUR) 
GROUP BY HOUR
ORDER BY HOUR;