-- 코드를 작성해주세요
WITH EMP_GRADE AS (
    SELECT EMP_NO,  CASE
        WHEN AVG(SCORE) >= 96 THEN 'S'
        WHEN AVG(SCORE) >= 90 THEN 'A'
        WHEN AVG(SCORE) >= 80 THEN 'B'
        ELSE 'C'
        END AS 'GRADE'
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT HE.EMP_NO, HE.EMP_NAME, EG.GRADE, CASE EG.GRADE
    WHEN 'S' THEN HE.SAL * 0.2
    WHEN 'A' THEN HE.SAL * 0.15
    WHEN 'B' THEN HE.SAL * 0.1
    WHEN 'C' THEN HE.SAL * 0
    END AS BONUS
FROM HR_EMPLOYEES AS HE JOIN EMP_GRADE AS EG ON (HE.EMP_NO = EG.EMP_NO)
ORDER BY HE.EMP_NO;