WITH MOST_MEMBER AS (
    SELECT RR.MEMBER_ID, COUNT(RR.MEMBER_ID) AS CNT, MP.MEMBER_NAME
    FROM REST_REVIEW AS RR JOIN MEMBER_PROFILE AS MP ON(RR.MEMBER_ID = MP.MEMBER_ID)
    GROUP BY RR.MEMBER_ID
    ORDER BY CNT DESC
    LIMIT 1
)

SELECT MM.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MOST_MEMBER AS MM JOIN REST_REVIEW AS RR ON(MM.MEMBER_ID = RR.MEMBER_ID)
ORDER BY REVIEW_DATE, RR.REVIEW_TEXT;