WITH BIGGEST AS (
    SELECT MAX(SIZE_OF_COLONY) AS 'BIGCOL', YEAR(DIFFERENTIATION_DATE) AS 'YEAR'
      FROM ECOLI_DATA 
     GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR(A.DIFFERENTIATION_DATE) AS 'YEAR'
        , (B.BIGCOL - A.SIZE_OF_COLONY) AS 'YEAR_DEV'
        , A.ID 
  FROM ECOLI_DATA AS A
  JOIN BIGGEST AS B ON (YEAR(A.DIFFERENTIATION_DATE) = B.YEAR)
 ORDER BY YEAR(A.DIFFERENTIATION_DATE), YEAR_DEV;