SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO AS A JOIN FISH_NAME_INFO AS B ON (A.FISH_TYPE = B.FISH_TYPE)
WHERE (A.FISH_TYPE, A.LENGTH) = (
        SELECT C.FISH_TYPE, MAX(C.LENGTH)
        FROM FISH_INFO AS C
        WHERE C.FISH_TYPE = A.FISH_TYPE
    )
ORDER BY A.ID;