-- 코드를 작성해주세요
WITH FRONT AS (
    SELECT A.ID, A.SKILL_CODE, B.NAME, B.CODE
    FROM DEVELOPERS AS A JOIN SKILLCODES AS B
    WHERE B.CATEGORY = 'FRONT END'
    AND A.SKILL_CODE & B.CODE = B.CODE
)
, ANSWER AS (
    SELECT CASE 
    WHEN ((SELECT COUNT(*) FROM FRONT AS F WHERE F.ID = D.ID) > 0)
    && (D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') 
        = (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python'))
    THEN 'A'
    WHEN D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') 
    = (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')
    THEN 'B'
    WHEN (SELECT COUNT(*) FROM FRONT AS F WHERE F.ID = D.ID) > 0 
    THEN 'C'
    END AS GRADE, D.ID, D.EMAIL
    FROM DEVELOPERS AS D
    ORDER BY GRADE, D.ID
)

SELECT * FROM ANSWER WHERE GRADE IS NOT NULL;